// Interactive body map for the Exercises tab.
// Offline SVG silhouettes (front + back) with:
//  - Fine muscle zones (quads / glutes / hams / calves / lats / …)
//  - Recently-trained heat overlay from logged sets
//  - Category + muscle-tag filtering
window.BodyMap = (function () {
  /**
   * Zone definitions.
   * - category: parent library category (for chip sync)
   * - muscleMatch: regex against exercise.muscles + name (fine filter)
   * - coarse: if true, filter by category only (whole group)
   * - views: which silhouettes show this zone
   */
  const ZONES = {
    // —— Upper body ——
    shoulders: {
      label: "Shoulders",
      category: "shoulders",
      coarse: true,
      muscleMatch: /deltoid|shoulder/i,
      views: ["front", "back"],
      badge: { front: { x: 166, y: 104 }, back: { x: 166, y: 104 } }
    },
    chest: {
      label: "Chest",
      category: "chest",
      coarse: true,
      muscleMatch: /pector|chest/i,
      views: ["front"],
      badge: { front: { x: 110, y: 116 } }
    },
    arms: {
      label: "Arms",
      category: "arms",
      coarse: true,
      muscleMatch: /bicep|tricep|forearm|brachial/i,
      views: ["front", "back"],
      badge: { front: { x: 46, y: 196 }, back: { x: 46, y: 196 } }
    },
    // —— Back splits ——
    upper_back: {
      label: "Upper back",
      category: "back",
      muscleMatch: /trap|rhomboid|upper back|rear deltoid|external rotator/i,
      views: ["back"],
      badge: { back: { x: 110, y: 96 } }
    },
    lats: {
      label: "Lats",
      category: "back",
      muscleMatch: /\blats?\b|latissimus/i,
      views: ["back"],
      badge: { back: { x: 110, y: 148 } }
    },
    lower_back: {
      label: "Lower back",
      category: "back",
      muscleMatch: /erector|lower back|quadratus/i,
      views: ["back"],
      badge: { back: { x: 110, y: 206 } }
    },
    // Keep a whole-back zone for the coarse "Back" chip (not drawn as its own shape;
    // used when chip selects category back → highlight all back zones)
    back: {
      label: "Back",
      category: "back",
      coarse: true,
      muscleMatch: /lat|rhomboid|traps?|erector|back/i,
      views: [], // not a single drawable region
      badge: {}
    },
    // —— Core ——
    core: {
      label: "Core",
      category: "core",
      coarse: true,
      muscleMatch: /abdominal|oblique|core|hip flexor|quadratus/i,
      views: ["front"],
      badge: { front: { x: 110, y: 188 } }
    },
    // —— Legs splits ——
    quads: {
      label: "Quads",
      category: "legs",
      muscleMatch: /quad/i,
      views: ["front"],
      badge: { front: { x: 110, y: 286 } }
    },
    glutes: {
      label: "Glutes",
      category: "legs",
      muscleMatch: /glute/i,
      views: ["back"],
      badge: { back: { x: 110, y: 254 } }
    },
    hams: {
      label: "Hamstrings",
      category: "legs",
      muscleMatch: /hamstring/i,
      views: ["back"],
      badge: { back: { x: 110, y: 318 } }
    },
    calves: {
      label: "Calves",
      category: "legs",
      muscleMatch: /calf|calves|gastroc|soleus/i,
      views: ["front", "back"],
      badge: { front: { x: 110, y: 392 }, back: { x: 110, y: 392 } }
    },
    // Coarse legs (chip only)
    legs: {
      label: "Legs",
      category: "legs",
      coarse: true,
      muscleMatch: /quad|hamstring|glute|calf|calves|adductor|abductor|hip/i,
      views: [],
      badge: {}
    }
  };

  //
  // Anatomical geometry — redrawn July 2026 to match the dark-silhouette
  // reference (solid figure, fine light muscle-contour lines).
  // viewBox 0 0 220 480. Generated by tools/build-map.js — edit there, not here.
  //
  const BODY_OUTLINE =
    "M110 8 C122 8 130 17 130 30 C131 33 132 38 130 42 C128 50 124 54 118 57 L118 67 C123 71 134 74 144 77 C156 81 166 87 171 95 C177 102 180 112 179 122 C178 130 175 137 172 143 C175 154 178 167 179 180 C183 192 185 206 184 220 C183 229 182 236 181 242 C186 249 190 258 191 267 C192 275 187 279 181 274 C176 268 171 258 168 249 C166 241 165 233 164 224 C163 210 161 196 159 184 C156 170 153 156 150 144 C147 132 145 122 142 114 C141 111 140 109 139 108 C142 122 143 138 141 154 C138 168 135 180 136 192 C137 204 141 215 145 227 C148 243 148 263 144 285 C142 301 139 317 138 331 C138 341 139 349 140 357 C142 369 141 385 138 400 C136 412 134 424 134 433 C135 442 139 449 145 455 C148 460 146 465 139 465 L118 465 C113 465 111 461 112 455 C113 447 113 440 112 433 C111 422 112 412 113 402 C116 388 117 372 115 357 C113 347 112 339 113 331 C115 315 117 297 118 281 C119 265 119 250 117 242 C115 238 113 236 110 236 C107 236 105 238 103 242 C101 250 101 265 102 281 C103 297 105 315 107 331 C108 339 107 347 105 357 C103 372 104 388 107 402 C108 412 109 422 108 433 C107 440 107 447 108 455 C109 461 107 465 102 465 L81 465 C74 465 72 460 75 455 C81 449 85 442 86 433 C86 424 84 412 82 400 C79 385 78 369 80 357 C81 349 82 341 82 331 C81 317 78 301 76 285 C72 263 72 243 75 227 C79 215 83 204 84 192 C85 180 82 168 79 154 C77 138 78 122 81 108 C80 109 79 111 78 114 C75 122 73 132 70 144 C67 156 64 170 61 184 C59 196 57 210 56 224 C55 233 54 241 52 249 C49 258 44 268 39 274 C33 279 28 275 29 267 C30 258 34 249 39 242 C38 236 37 229 36 220 C35 206 37 192 41 180 C42 167 45 154 48 143 C45 137 42 130 41 122 C40 112 43 102 49 95 C54 87 64 81 76 77 C86 74 97 71 102 67 L102 57 C96 54 92 50 90 42 C88 38 89 33 90 30 C90 17 98 8 110 8 Z";

  const GEOMETRY = {
    front: {
      silhouette: [BODY_OUTLINE],
      detail: [
        "M92 92 Q101 98 109 95",
        "M128 92 Q119 98 111 95",
        "M110 96 L110 143",
        "M110 150 L110 226",
        "M95 164 Q103 160 109 161",
        "M125 164 Q117 160 111 161",
        "M94 181 Q103 177 109 178",
        "M126 181 Q117 177 111 178",
        "M95 198 Q103 194 109 195",
        "M125 198 Q117 194 111 195",
        "M91 160 Q87 178 93 198",
        "M129 160 Q133 178 127 198",
        "M93 224 Q102 234 109 235",
        "M127 224 Q118 234 111 235",
        "M106 60 L107 70",
        "M114 60 L113 70",
        "M160 158 Q165 172 166 186",
        "M60 158 Q55 172 54 186",
        "M170 196 Q174 210 173 226",
        "M50 196 Q46 210 47 226",
        "M128 252 Q133 288 129 322",
        "M92 252 Q87 288 91 322",
        "M121 256 Q123 288 121 320",
        "M99 256 Q97 288 99 320",
        "M124 338 Q129 344 125 350",
        "M96 338 Q91 344 95 350",
        "M123 360 Q126 392 121 426",
        "M97 360 Q94 392 99 426"
      ],
      regions: {
        shoulders: [
          { type: "path", d: "M146 82 C158 84 168 90 172 99 C176 107 177 116 176 125 C175 133 173 139 171 143 C163 140 156 133 152 123 C148 113 146 96 146 82 Z" },
          { type: "path", d: "M74 82 C62 84 52 90 48 99 C44 107 43 116 44 125 C45 133 47 139 49 143 C57 140 64 133 68 123 C72 113 74 96 74 82 Z" }
        ],
        chest: [
          { type: "path", d: "M111 92 C123 90 136 92 143 99 C148 105 149 116 146 126 C143 136 134 142 124 143 C116 144 111 140 110 132 L110 94 Z" },
          { type: "path", d: "M109 92 C97 90 84 92 77 99 C72 105 71 116 74 126 C77 136 86 142 96 143 C104 144 109 140 110 132 L110 94 Z" }
        ],
        arms: [
          { type: "path", d: "M171 146 C174 156 177 168 178 180 C182 193 183 206 183 219 C182 228 181 236 180 241 C175 243 171 246 168 248 C166 240 165 231 164 223 C163 209 161 196 159 185 C156 171 153 158 151 148 C157 149 165 149 171 146 Z" },
          { type: "path", d: "M49 146 C46 156 43 168 42 180 C38 193 37 206 37 219 C38 228 39 236 40 241 C45 243 49 246 52 248 C54 240 55 231 56 223 C57 209 59 196 61 185 C64 171 67 158 69 148 C63 149 55 149 49 146 Z" }
        ],
        core: [
          { type: "path", d: "M110 146 C118 146 127 148 133 153 C137 162 137 176 135 190 C133 206 128 220 121 229 C117 233 112 234 110 234 C108 234 103 233 99 229 C92 220 87 206 85 190 C83 176 83 162 87 153 C93 148 102 146 110 146 Z" }
        ],
        quads: [
          { type: "path", d: "M118 240 C127 236 137 240 142 248 C146 262 145 282 142 298 C140 312 138 324 136 332 C129 337 120 336 116 330 C114 312 115 292 116 274 C117 260 118 249 118 240 Z" },
          { type: "path", d: "M102 240 C93 236 83 240 78 248 C74 262 75 282 78 298 C80 312 82 324 84 332 C91 337 100 336 104 330 C106 312 105 292 104 274 C103 260 102 249 102 240 Z" }
        ],
        calves: [
          { type: "path", d: "M116 356 C122 348 131 348 137 356 C141 368 140 386 137 400 C135 411 133 421 132 430 C127 434 120 434 116 429 C114 419 113 409 114 400 C116 386 117 370 116 356 Z" },
          { type: "path", d: "M104 356 C98 348 89 348 83 356 C79 368 80 386 83 400 C85 411 87 421 88 430 C93 434 100 434 104 429 C106 419 107 409 106 400 C104 386 103 370 104 356 Z" }
        ]
      }
    },
    back: {
      silhouette: [BODY_OUTLINE],
      detail: [
        "M110 70 L110 178",
        "M110 78 L120 94",
        "M110 78 L100 94",
        "M98 104 Q92 112 95 122",
        "M122 104 Q128 112 125 122",
        "M126 134 Q122 156 117 172",
        "M94 134 Q98 156 103 172",
        "M160 156 Q166 170 168 184",
        "M60 156 Q54 170 52 184",
        "M170 198 Q174 212 173 228",
        "M50 198 Q46 212 47 228",
        "M88 272 Q98 279 108 275",
        "M132 272 Q122 279 112 275",
        "M126 292 Q128 318 126 348",
        "M94 292 Q92 318 94 348",
        "M124 362 Q127 382 124 400",
        "M96 362 Q93 382 96 400",
        "M117 404 Q124 409 131 403",
        "M103 404 Q96 409 89 403"
      ],
      regions: {
        shoulders: [
          { type: "path", d: "M146 82 C158 84 168 90 172 99 C176 107 177 116 176 125 C175 133 173 139 171 143 C163 140 156 133 152 123 C148 113 146 96 146 82 Z" },
          { type: "path", d: "M74 82 C62 84 52 90 48 99 C44 107 43 116 44 125 C45 133 47 139 49 143 C57 140 64 133 68 123 C72 113 74 96 74 82 Z" }
        ],
        arms: [
          { type: "path", d: "M171 146 C174 156 177 168 178 180 C182 193 183 206 183 219 C182 228 181 236 180 241 C175 243 171 246 168 248 C166 240 165 231 164 223 C163 209 161 196 159 185 C156 171 153 158 151 148 C157 149 165 149 171 146 Z" },
          { type: "path", d: "M49 146 C46 156 43 168 42 180 C38 193 37 206 37 219 C38 228 39 236 40 241 C45 243 49 246 52 248 C54 240 55 231 56 223 C57 209 59 196 61 185 C64 171 67 158 69 148 C63 149 55 149 49 146 Z" }
        ],
        calves: [
          { type: "path", d: "M116 356 C122 348 131 348 137 356 C141 368 140 386 137 400 C135 411 133 421 132 430 C127 434 120 434 116 429 C114 419 113 409 114 400 C116 386 117 370 116 356 Z" },
          { type: "path", d: "M104 356 C98 348 89 348 83 356 C79 368 80 386 83 400 C85 411 87 421 88 430 C93 434 100 434 104 429 C106 419 107 409 106 400 C104 386 103 370 104 356 Z" }
        ],
        upper_back: [
          { type: "path", d: "M110 72 C114 72 118 74 122 78 C131 82 140 87 145 94 C148 100 148 108 145 114 C138 120 129 124 121 126 C114 128 111 123 110 117 C109 123 106 128 99 126 C91 124 82 120 75 114 C72 108 72 100 75 94 C80 87 89 82 98 78 C102 74 106 72 110 72 Z" }
        ],
        lats: [
          { type: "path", d: "M110 126 C118 124 128 121 136 117 C140 125 141 136 139 148 C137 161 132 171 125 178 C120 183 113 183 110 176 C107 183 100 183 95 178 C88 171 83 161 81 148 C79 136 80 125 84 117 C92 121 102 124 110 126 Z" }
        ],
        lower_back: [
          { type: "path", d: "M110 182 C115 182 120 185 122 190 C124 202 123 213 120 222 C117 228 113 230 110 230 C107 230 103 228 100 222 C97 213 96 202 98 190 C100 185 105 182 110 182 Z" }
        ],
        glutes: [
          { type: "path", d: "M110 232 C120 228 132 230 139 238 C143 248 142 262 136 272 C130 280 120 282 113 276 C111 274 110 271 110 268 C110 271 109 274 107 276 C100 282 90 280 84 272 C78 262 77 248 81 238 C88 230 100 228 110 232 Z" }
        ],
        hams: [
          { type: "path", d: "M116 284 C124 280 134 282 140 288 C143 300 142 316 139 330 C137 342 134 350 131 354 C125 358 118 357 115 352 C114 336 114 318 115 304 C115 296 116 289 116 284 Z" },
          { type: "path", d: "M104 284 C96 280 86 282 80 288 C77 300 78 316 81 330 C83 342 86 350 89 354 C95 358 102 357 105 352 C106 336 106 318 105 304 C105 296 104 289 104 284 Z" }
        ]
      }
    }
  };

  /** Does an exercise belong to this zone? */
  function exerciseMatchesZone(ex, zoneId) {
    const z = ZONES[zoneId];
    if (!z) return false;
    if (z.coarse) {
      return (ex.category || "") === z.category;
    }
    const hay = `${ex.name || ""} ${(ex.muscles || []).join(" ")}`;
    if (z.muscleMatch && z.muscleMatch.test(hay)) return true;
    // Fallback: same category and no conflicting fine match elsewhere is too loose —
    // only count muscle match for fine zones.
    return false;
  }

  /** Count exercises per zone id. */
  function countByZone(exercises) {
    const counts = {};
    for (const id of Object.keys(ZONES)) {
      counts[id] = exercises.filter(ex => exerciseMatchesZone(ex, id)).length;
    }
    return counts;
  }

  /**
   * Heat intensity 0–1 per zone from recent completed sets.
   * @param {Array} workouts completed workouts
   * @param {Map|Object} exerciseById
   * @param {number} days lookback
   */
  function heatFromWorkouts(workouts, exerciseById, days = 14) {
    const cutoff = new Date();
    cutoff.setDate(cutoff.getDate() - days);
    const sets = {};
    for (const id of Object.keys(ZONES)) sets[id] = 0;

    const getDef = (id) => {
      if (!exerciseById) return null;
      if (typeof exerciseById.get === "function") return exerciseById.get(id);
      return exerciseById[id];
    };

    for (const w of workouts || []) {
      if (!w.completedAt) continue;
      const d = w.date ? new Date(w.date) : new Date(w.completedAt);
      if (d < cutoff) continue;
      for (const ex of (w.exercises || [])) {
        const def = getDef(ex.exerciseId) || {
          id: ex.exerciseId,
          name: ex.name || "",
          category: ex.category || "",
          muscles: ex.muscles || []
        };
        // Prefer library definition muscles
        const merged = {
          name: def.name || ex.name || "",
          category: def.category || ex.category || "",
          muscles: (def.muscles && def.muscles.length) ? def.muscles : (ex.muscles || [])
        };
        const done = (ex.sets || []).filter(s => s.done).length || (ex.sets || []).length || 0;
        if (!done) continue;
        for (const id of Object.keys(ZONES)) {
          if (exerciseMatchesZone(merged, id)) sets[id] += done;
        }
      }
    }

    const max = Math.max(1, ...Object.values(sets));
    const heat = {};
    for (const id of Object.keys(sets)) {
      heat[id] = sets[id] / max; // 0–1
      heat[id + "_sets"] = sets[id];
    }
    return heat;
  }

  function svgEl(name, attrs) {
    const n = document.createElementNS("http://www.w3.org/2000/svg", name);
    if (attrs) {
      for (const [k, v] of Object.entries(attrs)) {
        if (v == null || v === false) continue;
        n.setAttribute(k, String(v));
      }
    }
    return n;
  }

  function appendPart(parent, part, className, extraAttrs) {
    let node;
    if (part.type === "ellipse") {
      node = svgEl("ellipse", {
        cx: part.cx, cy: part.cy, rx: part.rx, ry: part.ry,
        class: className, ...(extraAttrs || {})
      });
    } else {
      node = svgEl("path", { d: part.d, class: className, ...(extraAttrs || {}) });
    }
    parent.appendChild(node);
    return node;
  }

  /**
   * @param {object} opts
   * @param {(sel: {zoneId:string, category:string}) => void} opts.onSelect
   * @param {Record<string, number>} [opts.counts]
   * @param {Record<string, number>} [opts.heat]  zoneId → 0–1
   * @param {boolean} [opts.heatEnabled]
   * @param {string} [opts.activeZone]
   */
  function create(opts) {
    const onSelect = opts.onSelect || (() => {});
    let counts = opts.counts || {};
    let heat = opts.heat || {};
    let heatEnabled = opts.heatEnabled !== false;
    let activeZone = opts.activeZone || "all";
    let view = opts.view || "front";

    const root = document.createElement("div");
    root.className = "body-map";
    root.setAttribute("data-testid", "body-map");

    // Header: title + front/back
    const header = document.createElement("div");
    header.className = "body-map-header";

    const title = document.createElement("div");
    title.className = "body-map-title";
    title.textContent = "Body map";

    const toggle = document.createElement("div");
    toggle.className = "body-map-toggle";
    toggle.setAttribute("role", "group");
    toggle.setAttribute("aria-label", "Body view");

    const frontBtn = document.createElement("button");
    frontBtn.type = "button";
    frontBtn.className = "body-map-toggle-btn";
    frontBtn.textContent = "Front";
    frontBtn.setAttribute("data-testid", "body-map-front");

    const backBtn = document.createElement("button");
    backBtn.type = "button";
    backBtn.className = "body-map-toggle-btn";
    backBtn.textContent = "Back";
    backBtn.setAttribute("data-testid", "body-map-back");

    toggle.appendChild(frontBtn);
    toggle.appendChild(backBtn);
    header.appendChild(title);
    header.appendChild(toggle);
    root.appendChild(header);

    // Heat toolbar
    const tools = document.createElement("div");
    tools.className = "body-map-tools";

    const heatLabel = document.createElement("label");
    heatLabel.className = "body-map-heat-toggle";
    heatLabel.setAttribute("data-testid", "body-map-heat-toggle");
    const heatCb = document.createElement("input");
    heatCb.type = "checkbox";
    heatCb.checked = heatEnabled;
    heatCb.setAttribute("data-testid", "body-map-heat-checkbox");
    const heatText = document.createElement("span");
    heatText.textContent = "Recent training heat (14 days)";
    heatLabel.appendChild(heatCb);
    heatLabel.appendChild(heatText);
    tools.appendChild(heatLabel);

    const heatLegend = document.createElement("div");
    heatLegend.className = "body-map-heat-legend";
    heatLegend.innerHTML =
      '<span class="body-map-heat-swatch cold"></span>Quiet' +
      '<span class="body-map-heat-swatch warm"></span>' +
      '<span class="body-map-heat-swatch hot"></span>Busy';
    tools.appendChild(heatLegend);
    root.appendChild(tools);

    const stage = document.createElement("div");
    stage.className = "body-map-stage";
    root.appendChild(stage);

    const status = document.createElement("div");
    status.className = "body-map-status";
    status.setAttribute("data-testid", "body-map-status");
    root.appendChild(status);

    const legend = document.createElement("div");
    legend.className = "body-map-legend";
    legend.textContent = "Tap a muscle zone to filter. Tap again to clear. Finer zones on Back: lats, glutes, hams.";
    root.appendChild(legend);

    function zoneCount(id) {
      const n = counts[id];
      return typeof n === "number" ? n : 0;
    }

    function heatLevel(id) {
      if (!heatEnabled) return 0;
      const h = heat[id];
      return typeof h === "number" ? h : 0;
    }

    function heatClass(id) {
      if (!heatEnabled) return "";
      const h = heatLevel(id);
      if (h <= 0) return "heat-0";
      if (h < 0.25) return "heat-1";
      if (h < 0.5) return "heat-2";
      if (h < 0.75) return "heat-3";
      return "heat-4";
    }

    function statusText() {
      if (!activeZone || activeZone === "all") {
        return "Showing all exercises — tap a muscle zone";
      }
      const z = ZONES[activeZone];
      const label = z ? z.label : activeZone;
      const n = zoneCount(activeZone);
      const sets = heat[activeZone + "_sets"] || 0;
      let s = n > 0 ? `Showing ${label} · ${n} exercise${n === 1 ? "" : "s"}` : `Showing ${label}`;
      if (heatEnabled && sets > 0) {
        s += ` · ${sets} set${sets === 1 ? "" : "s"} in 14 days`;
      }
      return s;
    }

    function paintToggle() {
      frontBtn.classList.toggle("active", view === "front");
      backBtn.classList.toggle("active", view === "back");
      frontBtn.setAttribute("aria-pressed", view === "front" ? "true" : "false");
      backBtn.setAttribute("aria-pressed", view === "back" ? "true" : "false");
      root.classList.toggle("heat-on", heatEnabled);
    }

    function paintRegions() {
      // Which zone ids should appear selected?
      // Coarse category selection (chip) highlights all fine zones of that category.
      const active = activeZone || "all";
      const activeCat = (ZONES[active] && ZONES[active].category) || (active === "all" ? null : active);

      stage.querySelectorAll(".body-map-region").forEach(g => {
        const id = g.getAttribute("data-zone");
        const z = ZONES[id];
        let on = false;
        if (active === "all") on = false;
        else if (active === id) on = true;
        else if (z && ZONES[active] && ZONES[active].coarse && z.category === ZONES[active].category) on = true;
        else if (z && activeCat && id === active) on = true;
        // Selecting "back" chip → highlight upper_back + lats + lower_back
        else if (active === "back" && z && z.category === "back") on = true;
        else if (active === "legs" && z && z.category === "legs") on = true;
        else if (active === "arms" && id === "arms") on = true;
        else if (active === "shoulders" && id === "shoulders") on = true;
        else if (active === "chest" && id === "chest") on = true;
        else if (active === "core" && id === "core") on = true;

        g.classList.toggle("is-active", on);
        g.setAttribute("aria-pressed", on ? "true" : "false");

        // Mirror active state onto the zone's badge (lives on the top layer)
        const badge = stage.querySelector(`[data-zone-badge="${id}"]`);
        if (badge) badge.classList.toggle("is-active", on);

        // Heat class on parts
        const hc = heatClass(id);
        g.classList.remove("heat-0", "heat-1", "heat-2", "heat-3", "heat-4");
        if (hc) g.classList.add(hc);
      });

      const hasSel = !!(active && active !== "all");
      stage.classList.toggle("has-selection", hasSel);
      status.textContent = statusText();
      heatLegend.style.opacity = heatEnabled ? "1" : "0.35";
    }

    function preferredViewFor(zoneId) {
      const z = ZONES[zoneId];
      if (!z) return view;
      if (z.views.includes(view)) return view;
      if (z.views.includes("back")) return "back";
      if (z.views.includes("front")) return "front";
      // Coarse-only zones: pick a sensible view
      if (zoneId === "back") return "back";
      if (zoneId === "legs") return view;
      if (zoneId === "chest" || zoneId === "core") return "front";
      return view;
    }

    function selectZone(id) {
      const next = activeZone === id ? "all" : id;
      activeZone = next;
      // Auto-flip view when needed
      if (next !== "all") {
        const pref = preferredViewFor(next);
        if (pref !== view) {
          view = pref;
          paintToggle();
          renderSvg();
          // renderSvg calls paintRegions at end
        } else {
          paintRegions();
        }
      } else {
        paintRegions();
      }
      const z = ZONES[next];
      onSelect({
        zoneId: next,
        category: next === "all" ? "all" : (z ? z.category : next),
        coarse: next === "all" ? true : !!(z && z.coarse)
      });
    }

    function renderSvg() {
      stage.innerHTML = "";
      const geo = GEOMETRY[view] || GEOMETRY.front;

      const svg = svgEl("svg", {
        viewBox: "0 0 220 480",
        class: "body-map-svg",
        role: "img",
        "aria-label": `Body map, ${view} view`
      });

      // Soft ground under the feet
      svg.appendChild(svgEl("ellipse", {
        cx: 110, cy: 470, rx: 58, ry: 6,
        class: "body-map-ground"
      }));

      // Continuous anatomical silhouette (skin underlay)
      const under = svgEl("g", { class: "body-map-underlay", "aria-hidden": "true" });
      for (const d of (geo.silhouette || [])) {
        under.appendChild(svgEl("path", { d, class: "body-map-underlay-part" }));
      }
      svg.appendChild(under);

      // Interactive regions for this view
      const badgeLayer = svgEl("g", { class: "body-map-badges", "aria-hidden": "true" });
      const regionIds = Object.keys(geo.regions);
      for (const zoneId of regionIds) {
        const z = ZONES[zoneId];
        if (!z) continue;
        const parts = geo.regions[zoneId] || [];
        const g = svgEl("g", {
          class: "body-map-region",
          "data-zone": zoneId,
          role: "button",
          tabindex: "0",
          "aria-label": `${z.label}${zoneCount(zoneId) ? `, ${zoneCount(zoneId)} exercises` : ""}`,
          "aria-pressed": "false"
        });

        for (const part of parts) {
          appendPart(g, part, "body-map-region-part");
        }

        // Count badge (rendered on the top layer so contour lines never cross it)
        const pos = (z.badge && z.badge[view]) || null;
        const n = zoneCount(zoneId);
        if (pos && n > 0) {
          const badge = svgEl("g", { class: "body-map-badge", "data-zone-badge": zoneId, "aria-hidden": "true" });
          badge.appendChild(svgEl("circle", {
            cx: pos.x, cy: pos.y, r: 10,
            class: "body-map-badge-bg"
          }));
          const t = svgEl("text", {
            x: pos.x, y: pos.y + 3.5,
            "text-anchor": "middle",
            class: "body-map-badge-text"
          });
          t.textContent = String(n);
          badge.appendChild(t);
          badgeLayer.appendChild(badge);
        }

        g.addEventListener("click", (e) => {
          e.preventDefault();
          selectZone(zoneId);
        });
        g.addEventListener("keydown", (e) => {
          if (e.key === "Enter" || e.key === " ") {
            e.preventDefault();
            selectZone(zoneId);
          }
        });

        svg.appendChild(g);
      }

      // Fine muscle-contour lines drawn over the zones (non-interactive)
      if (geo.detail && geo.detail.length) {
        const detailG = svgEl("g", { class: "body-map-detail", "aria-hidden": "true" });
        for (const d of geo.detail) {
          detailG.appendChild(svgEl("path", {
            d,
            class: "body-map-detail-line",
            fill: "none"
          }));
        }
        svg.appendChild(detailG);
      }

      // Count badges on top so no lines cross them
      svg.appendChild(badgeLayer);

      stage.appendChild(svg);
      paintRegions();
    }

    frontBtn.addEventListener("click", () => {
      if (view === "front") return;
      view = "front";
      paintToggle();
      renderSvg();
    });
    backBtn.addEventListener("click", () => {
      if (view === "back") return;
      view = "back";
      paintToggle();
      renderSvg();
    });
    heatCb.addEventListener("change", () => {
      heatEnabled = heatCb.checked;
      paintToggle();
      paintRegions();
      onSelect({
        zoneId: activeZone,
        category: activeZone === "all" ? "all" : (ZONES[activeZone] ? ZONES[activeZone].category : activeZone),
        coarse: activeZone === "all" ? true : !!(ZONES[activeZone] && ZONES[activeZone].coarse),
        heatOnly: true
      });
    });

    paintToggle();
    renderSvg();

    return {
      el: root,
      ZONES,
      setActive(zoneId) {
        activeZone = zoneId || "all";
        // Flip view if needed for visibility
        if (activeZone !== "all") {
          const pref = preferredViewFor(activeZone);
          if (pref !== view) {
            view = pref;
            paintToggle();
            renderSvg();
            return;
          }
        }
        paintRegions();
      },
      setView(v) {
        if (v !== "front" && v !== "back") return;
        if (view === v) return;
        view = v;
        paintToggle();
        renderSvg();
      },
      setHeat(nextHeat) {
        heat = nextHeat || {};
        paintRegions();
      },
      setCounts(nextCounts) {
        counts = nextCounts || {};
        renderSvg();
      },
      setHeatEnabled(on) {
        heatEnabled = !!on;
        heatCb.checked = heatEnabled;
        paintToggle();
        paintRegions();
      },
      getActive() { return activeZone; }
    };
  }

  return {
    create,
    ZONES,
    exerciseMatchesZone,
    countByZone,
    heatFromWorkouts
  };
})();
